[build]
  command = "git submodule update --init --recursive && pnpm install --no-frozen-lockfile && hugo --minify"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.111.3"
  PNPM_FLAGS = "--no-frozen-lockfile"